# Generated by Django 2.1.7 on 2019-10-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.FloatField(default=None, max_length=20),
        ),
    ]
