# Generated by Django 2.1.7 on 2019-10-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20191001_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
