# Generated by Django 2.1.7 on 2019-10-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20191001_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
