# Generated by Django 2.2.1 on 2019-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_auto_20191002_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
