# Generated by Django 2.2.1 on 2019-11-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_auto_20191113_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.Product'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
